### ISSUE TITLE
connect_proxy.js

### ISSUE THREAD

**Issue by ShadySQL** [aws-samples/aws-dynamodb-mars-json-demo#1]
Loading "connect_proxy.js" tasks...ERROR

> > TypeError: The super constructor to `inherits` must not be null or undefined.

Running "serve" task
Warning: Task "configureProxies:server" not found. Use --force to continue.

Aborted due to warnings.

And the app blows up from that point on

**Comment by NoSQLKnowHow** [comment]
This repository is being archived. Sorry your question was not answered. The original owner of this repo left no one to take care of it.
