### ISSUE TITLE
jsonObjectToMap doesn't return proper Map<String, AttributeValue>

### ISSUE THREAD

**Issue by jaympatel1893** [aws-samples/aws-dynamodb-mars-json-demo#2]
If 
```
    {
    	"id": {
    		"s":"someId"
    	},
    	"version": {
    		"n":"1.0"
    	},
    	"otherData": {
    		"b":"someByteData"
    	}
    }
```
I read this as a string and convert into JsonNode first. 

Code to convert it into Map<>
```
ObjectMapper objectMapper = new ObjectMapper();    
JsonNode node = objectMapper.readTree(jsonString);
JacksonConverter converter = new JacksonConverterImpl();
Map<String, AttributeValue> map = converter.jsonObjectToMap(node);
```

So to fetch `someId` from above json, I have to fetch map inside the AttributeValue first. (`getM()`)
Then get the again get first value of the key. 
Shouldn't someId be fetchful from `getS()` directly in the original map?

**Comment by NoSQLKnowHow** [comment]
This repository is being archived. Sorry your question was not answered. The original owner of this repo left no one to take care of it.
